import * as dotenv from "dotenv";
dotenv.config();

import sgMail from "@sendgrid/mail";
sgMail.setApiKey(process.env.SENDGRID_API_KEY as string);

export const sendVerifyAccountEmail = async (data: {
  email: string;
  userId: string;
  otp: string;
}) => {
  const { email, userId, otp } = data;
  const msg = {
    to: email,
    from: "support@bongkonect.com",
    subject: "Bongkonect email verification",
    text:
      `Dear Friend\n\n` +
      `Welcome to Bongkonect. Bongkonect is a networking website for Bengali speaking people across the globe, ` +
      `providing registered users to create profile, search and post jobs, business listing, upload Bengali language video, ` +
      `banner and poster advertisement and stay connected.\n` +
      `We wish you a pleasant and responsible networking here on.\n` +
      `Your Email verification OTP is - ${otp}` +
      `\nFrom now on please login to your account using your email address and password.\n` +
      `Thank you\n` +
      `This is an autogenerated mail, please do not reply.\n\n` +
      `With about 250 million native and about 300 million total speakers worldwide, Bengali is one of the most spoken languages of the world.`,
  };
  try {
    await sgMail.send(msg);
  } catch (err) {
    console.log(err);
  }
};

export const sendResetPasswordEmail = async ({
  email,
  token,
}: {
  email: string;
  token: string;
}) => {
  const msg = {
    to: email,
    from: "support@bongkonect.com",
    subject: "Link to reset password",
    text:
      `You are receiving this because you have requested the reset of password for your account.\n\n` +
      `Plase click on the following link, or paste this into your browser to complete the process within one hour of receiving it:\n\n` +
      `${process.env.CLIENT_ORIGIN}/reset/${token}\n\n` +
      `If you did not receive this, please ignore this email and your password remain unchanged.\n`,
  };
  try {
    await sgMail.send(msg);
  } catch (err) {
    console.log(err);
  }
};
